### ISSUE TITLE
Add a Swipe to Refresh option

### ISSUE THREAD

**Issue by nivethsaran** [thepracticaldev/DEV-Android#76] opened 2020-05-20 06:07 UTC
When one is not connected to the internet, the app displays a "Web page not available" message. But, after the network connection is established, one has to restart the app. So, instead, it would be better to have a reload option.

**Possible Solution**

Add a SwipeRefreshLayout and enable it when there is no internet connection

**Comment by fdoxyz** [comment] 2020-05-20 14:18
Hi @nivethsaran thanks for the report! 

Without an active internet connection I can reproduce this on a fresh install or by deleting the app storage data from the settings. This because once the service worker has been loaded by browsing the site successfully (at least once) an offline page appears and the top icon kind of helps.

But I still agree that a way to reload the exact URL we were browsing is probably the best solution for both scenarios. As for the possible solution I think that even the swipe to reload might be obvious to a lot of people, but also maybe not for everyone. 

I think an elegant way to solve this could be to check when a request has failed to load. Then make use of [ConnectivityManager](https://developer.android.com/training/monitoring-device-state/connectivity-status-type) to automatically reload the requested URL when the connection has been reestablished (no user interaction needed in this case)

To our amazing contributors: issues labeled type: `bug` are always up for grabs. To claim an issue to work on, please leave a comment. If you've claimed the issue and need help, please ping me here and I'll do my best to follow up as soon as possible.

**Comment by nizarmah** [comment] 2020-05-25 15:32
Hello @fdoxyz, sorry I didn't claim that issue yet. I saw it yesterday and I was interested in applying it.

I did apply it, however, not using `ConnectivityManager`. Yet, it still works the way you want. If any of the pages fail to load because of the absence of an internet connection, the page is automatically refreshed/reloaded when the device is back online.

**Comment by fdoxyz** [comment] 2020-05-25 16:11
Hi @nizarmah, thanks for the PR! I'll take a look into it soon

**Comment by nizarmah** [comment] 2020-05-28 14:45
@fdoxyz should this issue be closed or is there a bot that will close it automatically on next release?

**Comment by fdoxyz** [comment] 2020-05-28 17:04
Once the new version is out on the store and we can confirm we're good here I'll do a manual sweep closing this one 👍🏼

**Closed** 2020-09-30 14:49 UTC
Labels: bug, good first issue, optimization
