### ISSUE TITLE
Stuck on Offline page upon start

### ISSUE THREAD

**Issue by samfcmc** [thepracticaldev/DEV-Android#36] opened 2019-06-08 15:56 UTC
**Describe the bug**
Two days ago, I tried to open the app and it just shows me the offline screen (see screenshot).

I have been using the app for more than a month without any issues. But since two days ago I always get this error. I can't do anything, like logout or something.

If I open Google Chrome and type "dev.to" I can use the web app without any problems. Only the apps returns me this error.

**To Reproduce**
I am sorry, I hate to tell you this but I really don't know how to reproduce. I was just using it and one day I tried and it started to show me the error screen. From that day, it always does that and I can't do anything.

I am a software developer and I hate when people report a bug and tell me they don't know how to reproduce... But it is the case here. 😞 

**Expected behavior**
Show the dev.to feed

**Screenshots**

![dev_to_error](https://user-images.githubusercontent.com/4904318/59149461-3b8fd280-8a0d-11e9-95b2-a5a880a9b62d.jpg)

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy S7 Edge
 - OS: Android 
 - Version 8.0.0

**Additional context**

I don't know what happened. Let me know what I can do to get more data to help you.

**Comment by maestromac** [comment] 2019-06-08 19:53
Thanks for the error report @samfcmc . Can you try uninstalling and reinstalling the app? Let me know if the error still persist.

**Comment by justinenz** [comment] 2019-06-09 21:06
**Describe the bug**
I have the same bug as @samfcmc 

**To Reproduce**
Unsure, seems to have started on its own?

**Expected behavior**
Show the dev.to feed

**Smartphone (please complete the following information):**

    Device: Samsung Galaxy Note 9
    OS: Android
    Version 9.0.0

**Additional context**
dev.to app version: 1.2
dev.to Beta: No

_First attempt at resolving_
Force closed dev.to app
Cleared dev.to app cache
Opened dev.to app
Results: offline screen persisted

_Second attempt at resolving_
Force closed dev.to app
Cleared dev.to app cache
Cleared dev.to app data
Opened dev.to app
Initial results: feed was shown
Closed dev.to app
Opened dev.to app
Final results: offline screen returned

_Third attempt at resolving_
Uninstall dev.to app
Install dev.to app
Opened dev.to app
Initial results: feed was shown
Closed dev.to app
Opened dev.to app
Final results: offline screen returned

**Comment by samfcmc** [comment] 2019-06-11 07:33
I reinstalled the app. I was able to login and see the feed. Later on, when I try to open the app again, the offline screen returns. I can only see the feed the first time I use it after installing the app.

**Comment by maestromac** [comment] 2019-06-11 21:14
I'm experiencing this issue too now. I'm going out of the limb to say that this is most likely caused by Service Worker.

**Comment by maestromac** [comment] 2019-06-12 20:46
Thanks for those infos @samfcmc . I've verified that this is indeed caused by Service Worker; It is being too aggressive with offline page. I will be deploying a tweak via the web app.

**Comment by samfcmc** [comment] 2019-06-15 16:26
@joshuadeguzman I don't need to turn off WiFi or data. After I closed it, it becomes unusable. I am closing it by touching the "Overview" on the bottom side of my phone and force the app to close. Then, I have to delete the app data to be able to use it again.

**Comment by sierisimo** [comment] 2019-06-19 06:20
I was trying to figure out in code this but it's hard because there's no special URL for the offline page and the app just renders a custom `webview`.

One thing that came up to my mind is to add a "reload" if the URL is the "_base url_" in the method `onStart` but this will lead to other kind of problems with the cache of the custom webview.

Another option could be: 
* checking for internet when the app is being paused
* if no connection happens store a value in the app
* next time the app opens, the app will check for this value
* if value is found, the app will force the reload of the webview.

That's the most that came to my mind right know, I'm not sure how the offline page of dev.to works.

If someone can share any further information with me I can give it a try to the fix.

**Comment by igagrock** [comment] 2019-06-21 07:53
Same here. OnePlus 3t.

**Comment by MSF-Jarvis** [comment] 2019-06-21 14:27
Exact same behaviour as @samfcmc, had to clear data to regain functionality. Appears the fix didn't work?

**Comment by sierisimo** [comment] 2019-06-21 18:15
The fix to this has to be achieved in the web team. For android the things we can achieve require to know the explicit URL or check on every launch for a reload of the webview.

Doing the reload of the webview will lead to more issues than the fix from the webworker

**Comment by MSF-Jarvis** [comment] 2019-06-21 18:26
I'm aware. I saw Mac land a Service Worker update in master (https://github.com/thepracticaldev/dev.to/commit/0af2a0a7dc941d0522c82373b1af0d7706649037) which was why I said what I did.

**Comment by maestromac** [comment] 2019-06-21 19:33
Yep the fix will have to be done on the web app. I'm channeling the conversation to here for the time being since I see higher occurrence through the mobile app. 

At the moment, I can't seem to reproduce the error at all on my OnePlus 6T Android 9.0.14. Perhaps using both WebViewClient and WebChromeClient is causing some conflict with SW? Whatever it is, it is causing [fetch](https://github.com/thepracticaldev/dev.to/blob/master/app/assets/javascripts/serviceworker.js.erb#L50) to fail immediately despite having a connection. The most drastic solution that might need to happen is to turn off Service Worker for mobile.

**Comment by maestromac** [comment] 2019-06-27 14:34
Judging by the bug's sudden appearance and how it's also affecting Facebook's browser, I believe this is a chromium bug https://bugs.chromium.org/p/chromium/issues/detail?id=977784

**Comment by maestromac** [comment] 2019-06-27 16:42
It seems like the fix was rolled out yesterday by the Chromium team and it will take a few days for everybody to receive it. If you are still hitting the offline page upon start, clearing the cache once or twice should resolve the it as per Chromium team's suggestion. 

I am keeping and eye on it if to see if there's any further action we need to take.

**Comment by MSF-Jarvis** [comment] 2019-06-27 16:46
Clearing cache seems to have resolved the problem on my end. Will be on the lookout for Chrome updates on my devices.

**Comment by neex-io** [comment] 2019-06-28 20:09
I cleaned the cache and reinstalled the app. It opened fine. I did not log in and the 2nd time around it was offline again.

**Comment by MSF-Jarvis** [comment] 2019-07-07 15:00
Haven't hit this again in the past week

**Comment by maestromac** [comment] 2019-07-09 14:54
Are you still experiencing this issue @neex-io ?

**Comment by MSF-Jarvis** [comment] 2019-07-09 17:01
And right on cue, stuck on offline page again 🤐

**Comment by sierisimo** [comment] 2019-09-06 05:30
Haven't faced the issue in a while… is still a thing?

**Comment by msfjarvis** [comment] 2019-09-06 06:27
Can confirm the issue hasn't showed up since my last comment.

**Comment by maestromac** [comment] 2019-09-06 13:39
Thank you for the update.

This issue is resolved

**Closed by maestromac** 2019-09-06 13:39 UTC
Labels: bug

**Comment by AhsabAli2000** [comment] 2021-02-28 10:28
This is happening today too on desktop brave
